// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: /src/index.coffee
  //  package: armazilla-util

  var lib;

  lib = require('./lib');

  module.exports = lib;

}).call(this);
