// Generated by CoffeeScript 2.7.0
(function() {
  // -*- coffee -*-

  //  file: src/lib/random-id.coffee
  //  package: armazilla-util

  // returns a randomized id string
  var random_id;

  random_id = function(obj, name) {
    name = name || obj.constructor.name;
    return `${name}_${Math.random().toString().slice(2)}`;
  };

  exports.random_id = random_id;

}).call(this);
